
:toc:

= Using the Test


:leveloffset: 1


= Introducing the Showcase App

Showcase apps demonstrate many features of {product-name}. To see these features:

. Set up the appropriate services as described in xref:setting-up-mobile-services-to-demonstrate-showcase-apps[].
. Set up the showcase app as described in xref:app[].
. Register your showcase app as described in link:{getting-started-guide-link}[Registering a Mobile App].
. Bind your {mobile-client} to the appropriate services as described in xref:binding[]
. Copy the `mobile-services.json` file to your IDE as described in xref:downloading-the-mobile-services-configuration-file[]
. Build and run your showcase app  as described in xref:build[].

[[setting-up-mobile-services-to-demonstrate-showcase-apps]]
== Setting up mobile services to demonstrate Showcase App features


.Procedure


. To demonstrate {keycloak-service}:


.. link:{idm-guide-link}#configuring-the-service[Set up the {keycloak-service} service].

.. Create a new user to authenticate using the link:{idm-docs-link}[{keycloak-service} documentation].

.. Set credentials for the created user. Follow the steps link:{idm-docs-link}[documentation].

+
For more information about features, see link:{idm-guide-link}[{keycloak-service} Service]


. To demonstrate {unifiedpush-service}, see link:{push-guide-link}[{unifiedpush-service} Service]

. To demonstrate {sync-service}, perform the Data Sync solution pattern available from the Solution Explorer.





[[setting-up-the-showcase-app]]
[#app]
== Setting Up the Showcase App

[discrete]
.Prerequisites

xref:setting-up-mobile-services-to-demonstrate-showcase-apps[]

[discrete]
.Procedure

1. Clone the showcase app and checkout the release tag {showcase-version}
+

[tabs]
====
Ionic::
+
--
[source,bash,subs="attributes"]
----
$ git clone https://github.com/aerogear/ionic-showcase.git
$ cd ionic-showcase
$ git checkout{showcase-version}
----
--
====

// TODO: fix link and numbering
[start=2]
. The following steps will help you enable Push Notifications in a showcase application.
+
[tabs]
====
Ionic::
+
--
. You will need to create a project on link:https://firebase.google.com/[Firebase^].
. Follow steps outlined link:https://support.google.com/firebase/answer/7015592?hl=en[here^] to download `google-services.json` from your Firebase project.
. Overwrite the file `app/google-services.json` with the `google-services.json` file you downloaded from
Firebase Cloud Messaging console.
--
////
Android::
+
--
. You will need to create a project on link:https://firebase.google.com/[Firebase^].
. Follow steps outlined link:https://support.google.com/firebase/answer/7015592?hl=en[here^] to download `google-services.json` from your Firebase project.
. Overwrite the file `app/google-services.json` with the `google-services.json` file you downloaded from
Firebase Cloud Messaging console.
--
iOS::
+
--
. Follow the link:https://help.apple.com/xcode/mac/current/#/devdfd3d04a1[official guide^] to enable push notifications for your Xcode project.

. Follow  the link:https://help.apple.com/developer-account/#/dev82a71386a[official guide^] to generate an APNs client TLS certificate and export the client TLS identity from your Mac.
+
NOTE: Make sure to protect the p12 file with a password.
+
NOTE: The exported p12 file with the password will be used later when binding your {mobile-client} to the {unifiedpush-service}.
--
Xamarin::
+
--
{unifiedpush-service} Service is not supported on Xamarin.
--
////
====

[#binding]
== Binding the Showcase {mobile-client} to {product-name}


. link:{idm-guide-link}#binding-a-mobile-client-with-the-identity-management-service[Bind the {mobile-client} to the {keycloak-service} service] if you want to demonstrate authentication.
. link:{push-guide-link}#binding-a-mobile-client-with-the-push-notifications-service[Bind the {mobile-client} to the {unifiedpush-service} service] if you want to demonstrate {unifiedpush-service}.
+
NOTE: This step also creates a variant as described in link:{push-guide-link}[ {unifiedpush-service} Service] terminology.

. link:{data-sync-guide-link}#sync-server-binding[Bind the {mobile-client} to the {sync-service} app] if you want to demonstrate {sync-service}.

[[downloading-the-mobile-services-configuration-file]]
= Downloading the Mobile Services Configuration File

. Open your {mobile-client} in Mobile Developer Console.
. Copy the `mobile-services.json` configuration to your clipboard.
 Save the contents of the clipboard to a new file called `mobile-services.json`.
+
NOTE: The mobile-services.json file is the link between the mobile services running on OpenShift and the mobile app you are developing. The mobile-services.json file provides all required configuration to initialise the various SDKs and connect them to the back-end services.
+
. Copy the contents of the `mobile-services.json` file into the `mobile-services.json` file located in `src`.



[[building-and-deploying-the-showcase-apps]]
[#build]
== Building and Running the Showcase App

. Build the Mobile App

[tabs]
====
Ionic::
+
--
[source,bash,subs="attributes"]
----
$ npm install
$ npm run ionic:build
----
--
====

[start=2]
. Run the Mobile App

[tabs]
====
Ionic::
+
--
To run the showcase app, use these commands:

[source,bash,subs="attributes"]
----
$ npm run ionic:android # to run on an Android device or emulator
$ npm run ionic:ios # to run on an iOS device or emulator
----

These commands would run the app on a device if connected or on the emulator if no device is connected.

Alternatively, you can use Cordova commands directly to specify the target:

[source,bash,subs="attributes"]
----
$ ionic cordova run android --device      # run on a connected device
$ ionic cordova run android --emulator    # run on the Android emulator
----
--
====

:leveloffset!:


// tag::excludeDownstream[]
[#certs]

:leveloffset: 1

//[[using-self-signed-certificates-in-mobile-clients]]
= Using Self-Signed Certificates in Mobile Apps

NOTE: Before you can run a mobile app and connect to {product-name}, you must configure self-signed certificates on the mobile device.

Throughout the development lifecycle of a mobile app, a common requirement is to integrate and connect with back-end services in a secure manner.
This is achieved using SSL/TLS.

However, in order for the client device to connect over SSL/TLS, it needs to trust the certificates used by the back-end services, which are signed by a certificate authority.
Most client devices have a list of well-known and trusted certificate authorities pre-installed and this allows the client devices to verify the certificates used by the back-end services.

A typical OpenShift development environment uses self-signed certificates that are not signed by any of the trusted certificate authorities.
In such an environment, the client devices cannot establish secure connections with the back-end services that are running on a local OpenShift cluster.

The suggested workaround is to manually extract the root certificate from the cluster, install it on the device, and make sure your application trusts the new certificate.

[[extracting-root-ca]]
== 1. Extracting the OpenShift Root Certificate Authority Cert

.. Log into OpenShift as the admin user:
+
[source,bash]
----
$ oc login -u system:admin
----

.. Run the following command:
+
[source,bash]
----
$ oc get secret router-certs --template='{{index .data "tls.crt"}}' -n default  |  \
base64 --decode | sed -e '1,/^-----END RSA PRIVATE KEY-----$/ d'  > /tmp/localcluster.crt
----
+
The resulting file is located in the `/tmp` directory.

[[installing-on-device]]
== 2. Installing the OpenShift Root Certificate Authority Cert on a Device

[tabs]
====
Android::
+
--
To install the cert on an Android emulator:

. https://support.google.com/android/answer/2819522?hl=en[Set screen lock] on the mobile device to allow for the installation of the certificate.

. Click on the *certificate file* and drag it onto the emulator. It should be copied to the _Downloads_ folder on the device.

. Install the certificate on your device:
+
.. To choose a file, navigate to _Settings > Security & location > Advanced > Encryption & credentials > Install from SD card_. From here, navigate to the _Downloads_ folder and you should see the certificate file.
.. Navigate to the `Downloads` folder and choose the certificate file.
The Android system detects the certificate and lets you install it. For more information, see the link:https://support.google.com/nexus/answer/2844832?hl=en[sample guide for Google Nexus devices].

To install the cert on a real Android device:

. https://support.google.com/android/answer/2819522?hl=en[Enable screen lock] on the mobile device to allow for the installation of the certificate.
. Copy the file to your device using one of the following methods:
+
* Email attachment (Recommended) - Email the certificate to an address accessible from the device and download the attachment.
* Cloud service - Use a cloud storage service such as Dropbox or Google Drive that is accessible from the device, and download from the device.
* USB - Attach the device to a computer and drag the certificate to a devices file system.
** Use the https://support.google.com/nexus/answer/2840804?hl=en[example guide for Google Nexus devices].
The procedure might be different for other devices.
** Use the link:https://developer.android.com/studio/command-line/adb[Android Debug Bridge (adb) documentation^] for the push command to push the certificate to the connected device, for example:
+
----
$ adb push /tmp/localcluster.crt /sdcard/Download/localcluster.crt
----
. Install the certificate on your device:
+
If you are use the email or cloud service method, you are prompted by the Android system automatically to install the file.
Follow the instructions to complete the process.
+
If you are using the USB approach, you must install the certificate manually:
+
.. Go to Settings > Security & location > Advanced > Encryption & credentials > Install from SD card.
You are prompted to choose a file.
.. Navigate to the `Downloads` folder and choose the certificate file.
The Android system detects the certificate and lets you install it. For more information, see the link:https://support.google.com/nexus/answer/2844832?hl=en[sample guide for Google Nexus devices].

To verify the self-signed certificate is installed correctly, use a browser on the device to open the OpenShift web console. You should not see any warnings or errors relating to the certificate.
--
iOS::
+
--
To install the cert on an iOS  simulator:

. Drag and drop the certificate file to the simulator, and use Safari to download the certificate to the simulator.

. Install the downloaded certificate:
+
.. Go to Settings > General > Profile.
You should see a profile with a name similar to `openshift-signer@xxxxxxx`.
.. Tap on the profile.
An *Install* button appears in the top right corner of the screen.
.. Tap the *Install* button to install the cert.

. Trust the installed certificate in iOS.
Go to Settings > General > About > Certificate Trust Settings, and enable the newly installed root certificate.
See the link:https://support.apple.com/en-us/HT204477[Apple support site] for more instructions.

To install the cert on a real iOS device:

. Enable https://support.apple.com/en-us/ht204060[Passcode] or https://support.apple.com/en-us/ht201371[TouchID] protection on the mobile device to ensure the certificate can be installed.
. Copy the file to your device using one of the following methods:
+
* Email attachment (Recommended) - Email the certificate to an address accessible from the device and download the attachment.
* Cloud service - Use a cloud storage service such as Dropbox or Google Drive that is accessible from the device, and download from the device.

. Add the certificate to your device:
+
When you download the certificate, the device should automatically detect a profile. Follow the on screen instructions to complete the process.

. Trust the installed certificate in iOS.
Go to Settings > General > About > Certificate Trust Settings, and enable the newly installed root certificate.
See the link:https://support.apple.com/en-us/HT204477[Apple support site] for more instructions.

To verify the self-signed certificate is installed correctly, use a browser on the deveice to open the OpenShift web console. You should not see any warnings or errors about the certificate.

--
====

[[trust-self-signed-cert]]
== 3. Trusting the Certificate In Your App.

In the previous procedures, you ensured that the operating system trusts the cert.
However, if you are using newer versions of the Android or iOS operating systems, you also need to update your mobile app to make sure it trusts the certificate.

[tabs]
====
Android::
+
--
. Create a `network_security_config.xml` file with the following code.
+
[source,xml]
----
<network-security-config>
  <base-config>
    <trust-anchors>
      <certificates src="user"/>
      <certificates src="system"/>
    </trust-anchors>
  </base-config>
</network-security-config>
----
+
Save this file in the following location:
* the root directory of the project for JavaScript apps

. Update the manifest file of your Android application to use this configuration.
.. If you are developing a Cordova application, add the following code the `config.xml` file in for the `android` platform:
+
[source,xml]
----
<resource-file src="network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
    <application android:networkSecurityConfig="@xml/network_security_config" />
</edit-config>
----
+
You also need to add `xmlns:android="http://schemas.android.com/apk/res/android"` to the `widget` tag in the same `config.xml` file.

For more information, check the link:https://developer.android.com/training/articles/security-config[Android network security configuration guide].
--
iOS::
+
--

. Add the `NSAllowsArbitraryLoads` key to the `Info.plist` file of your iOS project.
. Set the `NSAllowsArbitraryLoads` key to `Yes` to disable the App Transport Security (ATS) feature for your application.

NOTE: Only perform these steps for development or debug purposes, the resulting app will not pass the App Store review process.

For more information, see the https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW60[Apple developer docs].
--
====

:leveloffset!:
// end::excludeDownstream[]

[#features]
== Demonstrating the Test


:leveloffset: 2

= {sync-service}

NOTE: This is only available in the Cordova showcase app.

NOTE: To demonstrate all the features that {sync-service} offers, it's best to run the same app on multiple devices at the same time.

From the showcase app:

. Press the *Manage Tasks* menu item.
. View tasks created by other people and try to edit them. See them changed on other devices.
. Create new tasks and see them show up on other devices.
. Bring the device offline by switching to *Airplane Mode*, create a few more tasks and edit a few existing tasks. Then switch the device back online and see them changed on other devices.

:leveloffset!:

:leveloffset: 2}

= Security Services

== {device-security-service}

Device Trust page will check the mobile device for and give a security rating for the device based on the following checks

- Debugger Detected
- Root Access Detected
- Emulator Access Detected
- No Device Lock Enabled

To use Device Trust in the showcase app:

. Press the *Security* menu item.
. From the drop down press *Device Trust*.
. View the results of the Device security checks.

== {app-security-service} Service

Application Trust allows you to connect to the Mobile Security Service and that allows you to enable or disable a mobile app from the {app-security-service} console.

To use Application Trust in the showcase app:

. Press the *Security* menu item.
. From the drop down press *Application Trust*.
. Navigate to the Mobile Security Service link to set the enable/disable message as described in link:{app-security-service}#monitoring[Using the App Security Console].
. Press the *CHECK THE SECURITY SERVICE* button to check the message from the service.

:leveloffset!:

:leveloffset: 2}



= {unifiedpush-service}


. Send a push notification as described in
link:{push-guide-link}#sending[Sending a Push Notification]
. Launch the showcase app and view the notification.

:leveloffset!:

// tag::excludeDownstream[]
:leveloffset: 2



= {metrics-service}


. Launch the showcase app. It automatically sends xref:mobile-metrics.adoc#app[app and device metrics].
. Navigate to the {grafana-ui}, and view the metrics.
+
If you perform xref:device-security.adoc[device security] checks, related metrics are also displayed.

:leveloffset!:
// end::excludeDownstream[]
